const fs = require('fs');

const categories = [
    { id: 1, slug: 'supplements', name: 'Dietary Supplements', name_ar: 'مكملات غذائية', description: 'Real dietary supplements from catalog', description_ar: 'مكملات غذائية أصلية من الكتالوج', image: '/images/categories/supplements.jpg', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 2, slug: 'herbs', name: 'Medicinal Herbs', name_ar: 'أعشاب طبية', description: 'Organic medicinal herbs', description_ar: 'أعشاب طبية عضوية', image: '/images/categories/herbs.jpg', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 3, slug: 'oils', name: 'Medicinal Oils', name_ar: 'زيوت علاجية', description: 'Pure medicinal & essential oils', description_ar: 'زيوت علاجية وعطرية نقية', image: '/images/categories/oils.jpg', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 4, slug: 'honey', name: 'Natural Honey', name_ar: 'عسل طبيعي', description: '100% pure natural honey', description_ar: 'عسل طبيعي 100%', image: '/images/categories/honey.jpg', created_at: new Date().toISOString(), updated_at: new Date().toISOString() }
];

const folderMapping = {
    'dietary-supplements': 'supplements',
    'medicinal-herbs': 'herbs',
    'medicinal-oils': 'oils',
    'natural-honey': 'honey'
};

const baseDir = 'C:/Users/msi/Desktop/Ecommerce BioPara/clerk-nextjs/public/images';
let finalProducts = [];
let pid = 1;

const translations = {
    "Ashwagandha": "أشواجاندا", "Biotin": "بيوتين", "Collagen": "كولاجين",
    "L Glutathione": "إل-جلوتاثيون", "Magnesium": "مغنيسيوم", "Mastic Gum": "مستكة",
    "Multivitamins": "فيتامينات متعددة", "Omega 3 Fish Oil": "زيت السمك أوميغا 3",
    "Omega3 Supplement": "مكمل أوميغا 3", "Probiotic": "بروبيوتيك", "Shilajit": "شيلاجيت",
    "Vitamin D3 K2": "فيتامين D3 + K2", "Zinc": "زنك", "Chamomile": "بابونج",
    "Ginseng": "جينسنج", "Lavender": "لافندر (خزامى)", "Matcha": "ماتشا",
    "Matcha Powder": "مسحوق الماتشا", "Moringa": "مورينجا", "Roselle": "كركديه",
    "Spirulina": "سبيرولينا", "Argan": "أرغان", "Black Seed": "حبة البركة",
    "Castor": "خروع", "Coconut": "جوز الهند", "Eucalyptus": "كافور",
    "Olive": "زيتون", "Peppermint": "نعناع", "Rosemary": "إكليل الجبل",
    "Tea Tree": "شجرة الشاي", "Acacia": "طلح", "Black Forest": "الغابة السوداء",
    "Manuka": "مانوكا", "Mountain": "جبلي", "Sidr": "سدر", "White": "أبيض"
};

Object.entries(folderMapping).forEach(([folderName, catSlug]) => {
    const cat = categories.find(c => c.slug === catSlug);
    const dir = `${baseDir}/${folderName}`;
    if (fs.existsSync(dir)) {
        const files = fs.readdirSync(dir).filter(f => f.endsWith('.jpg') || f.endsWith('.png') || f.endsWith('.webp') || f.endsWith('.JPG'));
        files.forEach(file => {
            const nameBase = file.split('.')[0].replace(/-/g, ' ').replace(' herb', '').replace(' oil', '').replace(' honey', '');
            const name = nameBase.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');

            const trans = translations[name] || name;
            let nameAr = trans;
            let descAr = `منتج ${trans} عالي الجودة من الطبيعة. ممتاز لدعم الصحة والحيوية.`;

            if (catSlug === 'honey') {
                nameAr = `عسل ${trans} طبيعي`;
                descAr = `عسل ${trans} طبيعي نقي 100%، غني بالفوائد والمغذيات.`;
            } else if (catSlug === 'oils') {
                nameAr = `زيت ${trans} العضوي`;
                descAr = `زيت ${trans} العضوي النقي، مستخلص بعناية للحفاظ على فوائده.`;
            } else if (catSlug === 'herbs') {
                nameAr = `أعشاب ${trans}`;
                descAr = `أعشاب ${trans} طبيعية وعضوية، مثالية للاستخدام اليومي.`;
            } else if (catSlug === 'supplements') {
                nameAr = `مكمل ${trans}`;
                descAr = `مكمل ${trans} الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.`;
            }

            finalProducts.push({
                id: pid++,
                name: name,
                name_ar: nameAr,
                slug: `${cat.slug}-${file.split('.')[0]}`,
                description: `Premium ${name} for your health and wellbeing. Made with 100% natural ingredients.`,
                description_ar: descAr,
                price: Math.floor(Math.random() * (250 - 45) + 45),
                currency: 'MAD',
                stock: Math.floor(Math.random() * 50) + 10,
                images: [`/images/${folderName}/${file}`],
                image_url: `/images/${folderName}/${file}`,
                category_id: cat.id,
                is_active: true,
                featured: Math.random() > 0.5,
                created_at: new Date().toISOString(),
                updated_at: new Date().toISOString()
            });
        });
    }
});

const codeContent = `// THIS FILE IS AUTOMATICALLY GENERATED FROM PROJECT IMAGES
import { Category, Product } from './products'

export const demoCategories: Category[] = ${JSON.stringify(categories, null, 2)};

export const demoProducts: Product[] = ${JSON.stringify(finalProducts, null, 2)};
`;

fs.writeFileSync('C:/Users/msi/Desktop/Ecommerce BioPara/clerk-nextjs/lib/data/demo-data.ts', codeContent, 'utf8');
console.log('Successfully wrote ' + finalProducts.length + ' products to demo-data.ts');

// --- GENERATE SUPABASE SQL SEED FILE ---
const escapeSql = (str) => typeof str === 'string' ? str.replace(/'/g, "''") : str;
const escapeArray = (arr) => `ARRAY[${arr.map(a => `'${escapeSql(a)}'`).join(',')}]`;

let sqlContent = `-- ==========================================
-- BioPara: FULL Products Table Setup & Seed Data
-- Run this script in the Supabase SQL Editor
-- ==========================================

-- 1. Drop existing tables to ensure new columns are created
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;

-- 2. Create the categories table
CREATE TABLE public.categories (
    id bigint generated by default as identity primary key,
    name text not null,
    name_ar text,
    slug text not null unique,
    description text,
    description_ar text,
    image text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create the products table
CREATE TABLE public.products (
    id bigint generated by default as identity primary key,
    name text not null,
    name_ar text,
    slug text not null unique,
    description text,
    description_ar text,
    price numeric not null,
    currency text default 'MAD' not null,
    stock integer default 0 not null,
    images text[] default '{}'::text[],
    category_id bigint references public.categories(id) on delete cascade,
    is_active boolean default true not null,
    featured boolean default false not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Turn ON ROW LEVEL SECURITY
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies
DROP POLICY IF EXISTS "Enable read access for all users" ON public.products;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.categories;

CREATE POLICY "Enable read access for all users" 
ON public.products FOR SELECT USING ( true );

CREATE POLICY "Enable read access for all users" 
ON public.categories FOR SELECT USING ( true );

-- 6. Seed Categories
INSERT INTO public.categories (id, name, name_ar, slug, description, description_ar, image)
VALUES
`;

const catValues = categories.map(c =>
    `    (${c.id}, '${escapeSql(c.name)}', '${escapeSql(c.name_ar)}', '${escapeSql(c.slug)}', '${escapeSql(c.description)}', '${escapeSql(c.description_ar)}', '${escapeSql(c.image)}')`
);
sqlContent += catValues.join(',\n') + '\nON CONFLICT (slug) DO NOTHING;\n\n';

sqlContent += '-- 7. Seed Products\n';
sqlContent += 'INSERT INTO public.products (name, name_ar, slug, description, description_ar, price, currency, stock, images, category_id, is_active, featured)\nVALUES\n';

const prodValues = finalProducts.map(p =>
    `    ('${escapeSql(p.name)}', '${escapeSql(p.name_ar)}', '${escapeSql(p.slug)}', '${escapeSql(p.description)}', '${escapeSql(p.description_ar)}', ${p.price}, '${escapeSql(p.currency)}', ${p.stock}, ${escapeArray(p.images)}::text[], ${p.category_id}, ${p.is_active}, ${p.featured})`
);

sqlContent += prodValues.join(',\n') + '\nON CONFLICT (slug) DO NOTHING;\n\n-- Done!\n';

fs.writeFileSync('C:/Users/msi/Desktop/Ecommerce BioPara/clerk-nextjs/supabase_seed_products.sql', sqlContent, 'utf8');
console.log('Successfully wrote ' + finalProducts.length + ' products to supabase_seed_products.sql');

