export const products = [
  { "id": 1, "name": "عشبة الخزامى (Lavande)", "category": "Visage", "price": 25, "image": "/products1.png", "reviews": 120, "rating": 4.9, "description": "تهدئ وتريح البشرة، مثالية للعناية بالوجه." },
  { "id": 2, "name": "إكليل الجبل (Romarin)", "category": "Visage", "price": 18, "originalPrice": 25, "image": "/products2.png", "reviews": 95, "rating": 4.7, "description": "ينقي البشرة ويساعد على تقليل اللمعان." },
  { "id": 3, "name": "البابونج الطبيعي", "category": "Visage", "price": 30, "image": "/products3.png", "reviews": 85, "rating": 4.8, "description": "يلطف البشرة الحساسة ويمنحها إشراقة." },
  { "id": 4, "name": "زعتر جبل أطلس", "category": "Visage", "price": 35, "image": "/products4.png", "reviews": 110, "rating": 4.6, "description": "مضاد للأكسدة ومنقي طبيعي للبشرة." },
  { "id": 5, "name": "عشبة القدسين", "category": "Visage", "price": 65, "originalPrice": 80, "image": "/products5.png", "reviews": 45, "rating": 4.8, "description": "تساعد على توحيد لون البشرة وتجديدها." },
  { "id": 11, "name": "عشبة النافع", "category": "Visage", "price": 60, "image": "/products11.png", "reviews": 32, "rating": 4.6, "description": "معروفة بخصائصها المهدئة والمغذية للبشرة." },
  { "id": 13, "name": "عشبة المورينجا", "category": "Visage", "price": 45, "image": "/products13.png", "reviews": 88, "rating": 4.5, "description": "غنية بالفيتامينات وتساعد على حماية البشرة." },
  { "id": 14, "name": "الجينسنغ المغربي", "category": "Visage", "price": 90, "image": "/products14.png", "reviews": 102, "rating": 4.8, "description": "يعزز حيوية البشرة ويقاوم علامات التعب." },
  { "id": 15, "name": "ورق الزيتون", "category": "Visage", "price": 20, "image": "/products15.png", "reviews": 75, "rating": 4.3, "description": "يحمي البشرة من العوامل الخارجية بفضل مضادات الأكسدة." },
  { "id": 19, "name": "مسحوق الكركم", "category": "Visage", "price": 22, "originalPrice": 30, "image": "/products19.png", "reviews": 150, "rating": 4.8, "description": "يساعد على تفتيح البشرة ومنحها نضارة." },
  { "id": 20, "name": "بذور الشيا", "category": "Visage", "price": 40, "image": "/products17.png", "reviews": 130, "rating": 4.7, "description": "ترطب البشرة بعمق وتمنحها ملمسًا ناعمًا." },
  { "id": 21, "name": "عرق السوس", "category": "Visage", "price": 30, "image": "/products21.png", "reviews": 90, "rating": 4.4, "description": "يساعد على توحيد لون البشرة وتخفيف البقع الداكنة." },
  { "id": 6, "name": "زيت الأركان النقي", "category": "Parapharmacie", "price": 150, "originalPrice": 180, "image": "/products6.png", "reviews": 200, "rating": 4.9, "isNew": true, "description": "يغذي ويرطب الشعر والبشرة بعمق." },
  { "id": 7, "name": "سيروم فيتامين C", "category": "Parapharmacie", "price": 220, "image": "/products7.png", "reviews": 150, "rating": 4.7, "description": "يعزز إشراقة البشرة ويحارب علامات التقدم في السن." },
  { "id": 8, "name": "واقي شمس SPF50", "category": "Parapharmacie", "price": 120, "originalPrice": 140, "image": "/products8.png", "reviews": 180, "rating": 4.8, "description": "حماية عالية من أشعة الشمس UVA/UVB." },
  { "id": 9, "name": "صابون النيلة الزرقاء", "category": "Parapharmacie", "price": 45, "image": "/products9.png", "reviews": 90, "rating": 4.5, "description": "يفتح ويوحد لون البشرة بشكل طبيعي." },
  { "id": 10, "name": "كريم الترطيب الليلي", "category": "Parapharmacie", "price": 110, "image": "/products10.png", "reviews": 130, "rating": 4.6, "description": "يجدد ويرطب البشرة أثناء الليل." },
  { "id": 12, "name": "علاج البشارة", "category": "Parapharmacie", "price": 270, "image": "/products12.png", "reviews": 75, "rating": 4.4, "description": "حل فعال لمشاكل البشرة الشائعة." },
  { "id": 16, "name": "قناع الطين الأخضر", "category": "Parapharmacie", "price": 50, "originalPrice": 65, "image": "/products16.png", "reviews": 115, "rating": 4.6, "description": "ينقي البشرة الدهنية ويزيل الشوائب." },
  { "id": 17, "name": "ماء الورد المقطر", "category": "Parapharmacie", "price": 35, "image": "/products20.png", "reviews": 180, "rating": 4.9, "description": "ينعش ويهدئ البشرة، مثالي لجميع أنواع البشرة." },
  { "id": 18, "name": "زبدة الشيا الخام", "category": "Parapharmacie", "price": 80, "image": "/products18.png", "reviews": 95, "rating": 4.7, "description": "ترطيب عميق للجسم والمناطق الجافة." },
  { "id": 22, "name": "كريم النهار بفيتامين E", "category": "Parapharmacie", "price": 130, "image": "/products22.png", "reviews": 110, "rating": 4.5, "description": "يحمي البشرة من الأضرار اليومية ويرطبها." },
  { "id": 23, "name": "مقشر الجسم بالملح البحري", "category": "Parapharmacie", "price": 70, "originalPrice": 85, "image": "/products23.png", "reviews": 140, "rating": 4.6, "description": "يزيل الجلد الميت وينعم البشرة." }
]
