export const products = [
  { "id": 1, "name": "عشبة الخزامى (Lavande)", "category": "Visage", "price": 25, "image": "/products1.png", "reviews": 120, "rating": 4.9 },
  { "id": 2, "name": "إكليل الجبل (Romarin)", "category": "Visage", "price": 18, "originalPrice": 25, "image": "/products2.png", "reviews": 95, "rating": 4.7 },
  { "id": 3, "name": "البابونج الطبيعي", "category": "Visage", "price": 30, "image": "/products3.png", "reviews": 85, "rating": 4.8 },
  { "id": 4, "name": "زعتر جبل أطلس", "category": "Visage", "price": 35, "image": "/products4.png", "reviews": 110, "rating": 4.6 },
  { "id": 5, "name": "عشبة القدسين", "category": "Visage", "price": 65, "originalPrice": 80, "image": "/products5.png", "reviews": 45, "rating": 4.8 },
  { "id": 11, "name": "عشبة النافع", "category": "Visage", "price": 60, "image": "/products11.png", "reviews": 32, "rating": 4.6 },
  { "id": 13, "name": "عشبة المورينجا", "category": "Visage", "price": 45, "image": "/products13.png", "reviews": 88, "rating": 4.5 },
  { "id": 14, "name": "الجينسنغ المغربي", "category": "Visage", "price": 90, "image": "/products14.png", "reviews": 102, "rating": 4.8 },
  { "id": 15, "name": "ورق الزيتون", "category": "Visage", "price": 20, "image": "/products15.png", "reviews": 75, "rating": 4.3 },
  { "id": 19, "name": "مسحوق الكركم", "category": "Visage", "price": 22, "originalPrice": 30, "image": "/products19.png", "reviews": 150, "rating": 4.8 },
  { "id": 20, "name": "بذور الشيا", "category": "Visage", "price": 40, "image": "/products17.png", "reviews": 130, "rating": 4.7 },
  { "id": 21, "name": "عرق السوس", "category": "Visage", "price": 30, "image": "/products21.png", "reviews": 90, "rating": 4.4 },
  { "id": 6, "name": "زيت الأركان النقي", "category": "Parapharmacie", "price": 150, "originalPrice": 180, "image": "/products6.png", "reviews": 200, "rating": 4.9, "isNew": true },
  { "id": 7, "name": "سيروم فيتامين C", "category": "Parapharmacie", "price": 220, "image": "/products7.png", "reviews": 150, "rating": 4.7 },
  { "id": 8, "name": "واقي شمس SPF50", "category": "Parapharmacie", "price": 120, "originalPrice": 140, "image": "/products8.png", "reviews": 180, "rating": 4.8 },
  { "id": 9, "name": "صابون النيلة الزرقاء", "category": "Parapharmacie", "price": 45, "image": "/products9.png", "reviews": 90, "rating": 4.5 },
  { "id": 10, "name": "كريم الترطيب الليلي", "category": "Parapharmacie", "price": 110, "image": "/products10.png", "reviews": 130, "rating": 4.6 },
  { "id": 12, "name": "علاج البشارة", "category": "Parapharmacie", "price": 270, "image": "/products12.png", "reviews": 75, "rating": 4.4 },
  { "id": 16, "name": "قناع الطين الأخضر", "category": "Parapharmacie", "price": 50, "originalPrice": 65, "image": "/products16.png", "reviews": 115, "rating": 4.6 },
  { "id": 17, "name": "ماء الورد المقطر", "category": "Parapharmacie", "price": 35, "image": "/products20.png", "reviews": 180, "rating": 4.9 },
  { "id": 18, "name": "زبدة الشيا الخام", "category": "Parapharmacie", "price": 80, "image": "/products18.png", "reviews": 95, "rating": 4.7 },
  { "id": 22, "name": "كريم النهار بفيتامين E", "category": "Parapharmacie", "price": 130, "image": "/products22.png", "reviews": 110, "rating": 4.5 },
  { "id": 23, "name": "مقشر الجسم بالملح البحري", "category": "Parapharmacie", "price": 70, "originalPrice": 85, "image": "/products23.png", "reviews": 140, "rating": 4.6 }
];