-- ==========================================
-- BioPara: Products Table Setup & Seed Data
-- Run this script in the Supabase SQL Editor
-- ==========================================

-- 1. Drop existing tables to ensure new columns (like name_ar) are created
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;

-- 2. Create the categories table
CREATE TABLE public.categories (
    id bigint generated by default as identity primary key,
    name text not null,
    name_ar text,
    slug text not null unique,
    description text,
    description_ar text,
    image text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create the products table
CREATE TABLE public.products (
    id bigint generated by default as identity primary key,
    name text not null,
    name_ar text,
    slug text not null unique,
    description text,
    description_ar text,
    price numeric not null,
    currency text default 'SAR' not null,
    stock integer default 0 not null,
    images text[] default '{}'::text[],
    category_id bigint references public.categories(id) on delete cascade,
    is_active boolean default true not null,
    featured boolean default false not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Turn ON ROW LEVEL SECURITY
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies: Allow everyone to SELECT active products
DROP POLICY IF EXISTS "Enable read access for all users" ON public.products;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.categories;

CREATE POLICY "Enable read access for all users" 
ON public.products 
FOR SELECT 
USING ( true );

CREATE POLICY "Enable read access for all users" 
ON public.categories 
FOR SELECT 
USING ( true );

-- 6. Seed some initial categories & products
INSERT INTO public.categories (id, name, name_ar, slug, description_ar)
VALUES 
    (1, 'Herbs', 'أعشاب طبية', 'herbs', 'أعشاب طبيعية لمختلف الاستخدامات'),
    (2, 'Oils', 'زيوت طبيعية', 'oils', 'زيوت عضوية نقية')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, name_ar, slug, description, description_ar, price, stock, category_id, is_active, images)
VALUES 
    ('Mountain Honey', 'عسل جبلي حر', 'mountain-honey', 'Natural mountain honey from the Atlas', 'عسل جبلي طبيعي من جبال الأطلس يتميز بجودته العالية', 150.00, 50, 2, true, ARRAY['/images/categories/honey.jpg']),
    ('Organic Argan Oil', 'زيت أركان طبيعي', 'argan-oil', '100% Pure Argan Oil', 'زيت أركان عضوي نقي 100% ممتاز للبشرة', 220.00, 30, 2, true, ARRAY['/images/categories/oils.jpg']),
    ('Ginseng Root', 'جذور الجينسنج', 'ginseng', 'Premium Ginseng root', 'جينسنج أصلي للطاقة والحيوية', 180.00, 100, 1, true, ARRAY['/images/categories/herbs.jpg'])
ON CONFLICT (slug) DO NOTHING;

-- Done!
