// THIS FILE IS AUTOMATICALLY GENERATED FROM PROJECT IMAGES
import { Category, Product } from './products'

export const demoCategories: Category[] = [
  {
    "id": 1,
    "slug": "supplements",
    "name": "مكملات غذائية",
    "name_ar": "مكملات غذائية",
    "description": "Real dietary supplements from catalog",
    "description_ar": "مكملات غذائية أصلية من الكتالوج",
    "image": "/images/categories/supplements.jpg",
    "created_at": "2026-03-04T15:15:36.184Z",
    "updated_at": "2026-03-04T15:15:36.185Z"
  },
  {
    "id": 2,
    "slug": "herbs",
    "name": "أعشاب طبية",
    "name_ar": "أعشاب طبية",
    "description": "Organic medicinal herbs",
    "description_ar": "أعشاب طبية عضوية",
    "image": "/images/categories/herbs.jpg",
    "created_at": "2026-03-04T15:15:36.185Z",
    "updated_at": "2026-03-04T15:15:36.185Z"
  },
  {
    "id": 3,
    "slug": "oils",
    "name": "زيوت علاجية",
    "name_ar": "زيوت علاجية",
    "description": "Pure medicinal & essential oils",
    "description_ar": "زيوت علاجية وعطرية نقية",
    "image": "/images/categories/oils.jpg",
    "created_at": "2026-03-04T15:15:36.185Z",
    "updated_at": "2026-03-04T15:15:36.185Z"
  },
  {
    "id": 4,
    "slug": "honey",
    "name": "عسل طبيعي",
    "name_ar": "عسل طبيعي",
    "description": "100% pure natural honey",
    "description_ar": "عسل طبيعي 100%",
    "image": "/images/categories/honey.jpg",
    "created_at": "2026-03-04T15:15:36.185Z",
    "updated_at": "2026-03-04T15:15:36.185Z"
  }
  ,{
    "id": 5,
    "slug": "herbal-tea",
    "name": "شاي الأعشاب",
    "name_ar": "شاي الأعشاب",
    "description": "A selection of natural herbal teas for relaxation and health.",
    "description_ar": "تشكيلة من شاي الأعشاب الطبيعية للاسترخاء والصحة العامة.",
    "image": "/images/herbal tea/herb-tea-2.jpg",
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
];

export const demoProducts: Product[] = [
  {
    "id": 1,
    "name": "مكمل أشواجاندا",
    "name_ar": "مكمل أشواجاندا",
    "slug": "supplements-ashwagandha",
    "description": "Premium Ashwagandha for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل أشواجاندا الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 123,
    "original_price": null,
    "currency": "MAD",
    "stock": 42,
    "images": [
      "/images/dietary-supplements/ashwagandha.jpg"
    ],
    "image_url": "/images/dietary-supplements/ashwagandha.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 2,
    "name": "مكمل بيوتين",
    "name_ar": "مكمل بيوتين",
    "slug": "supplements-biotin",
    "description": "Premium Biotin for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل بيوتين الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 224,
    "original_price": null,
    "currency": "MAD",
    "stock": 58,
    "images": [
      "/images/dietary-supplements/biotin.jpg"
    ],
    "image_url": "/images/dietary-supplements/biotin.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 3,
    "name": "مكمل كولاجين",
    "name_ar": "مكمل كولاجين",
    "slug": "supplements-collagen",
    "description": "Premium Collagen for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل كولاجين الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 204,
    "original_price": null,
    "currency": "MAD",
    "stock": 33,
    "images": [
      "/images/dietary-supplements/collagen.jpg"
    ],
    "image_url": "/images/dietary-supplements/collagen.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 4,
    "name": "مكمل إل-جلوتاثيون",
    "name_ar": "مكمل إل-جلوتاثيون",
    "slug": "supplements-l-glutathione",
    "description": "Premium L Glutathione for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل إل-جلوتاثيون الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 141,
    "original_price": null,
    "currency": "MAD",
    "stock": 12,
    "images": [
      "/images/dietary-supplements/l-glutathione.jpg"
    ],
    "image_url": "/images/dietary-supplements/l-glutathione.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 5,
    "name": "مكمل مغنيسيوم",
    "name_ar": "مكمل مغنيسيوم",
    "slug": "supplements-magnesium",
    "description": "Premium Magnesium for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل مغنيسيوم الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 191,
    "original_price": null,
    "currency": "MAD",
    "stock": 35,
    "images": [
      "/images/dietary-supplements/magnesium.jpg"
    ],
    "image_url": "/images/dietary-supplements/magnesium.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 6,
    "name": "مكمل مستكة",
    "name_ar": "مكمل مستكة",
    "slug": "supplements-mastic-gum",
    "description": "Premium Mastic Gum for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل مستكة الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 145,
    "original_price": null,
    "currency": "MAD",
    "stock": 17,
    "images": [
      "/images/dietary-supplements/mastic-gum.jpg"
    ],
    "image_url": "/images/dietary-supplements/mastic-gum.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 7,
    "name": "مكمل فيتامينات متعددة",
    "name_ar": "مكمل فيتامينات متعددة",
    "slug": "supplements-multivitamins",
    "description": "Premium Multivitamins for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل فيتامينات متعددة الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 92,
    "original_price": null,
    "currency": "MAD",
    "stock": 19,
    "images": [
      "/images/dietary-supplements/multivitamins.jpg"
    ],
    "image_url": "/images/dietary-supplements/multivitamins.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 8,
    "name": "مكمل Omega 3 Fish",
    "name_ar": "مكمل Omega 3 Fish",
    "slug": "supplements-omega-3-fish-oil",
    "description": "Premium Omega 3 Fish for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل Omega 3 Fish الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 148,
    "original_price": null,
    "currency": "MAD",
    "stock": 21,
    "images": [
      "/images/dietary-supplements/omega-3-fish-oil.jpg"
    ],
    "image_url": "/images/dietary-supplements/omega-3-fish-oil.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 9,
    "name": "مكمل مكمل أوميغا 3",
    "name_ar": "مكمل مكمل أوميغا 3",
    "slug": "supplements-omega3-supplement",
    "description": "Premium Omega3 Supplement for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل مكمل أوميغا 3 الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 244,
    "original_price": null,
    "currency": "MAD",
    "stock": 34,
    "images": [
      "/images/dietary-supplements/omega3-supplement.jpg"
    ],
    "image_url": "/images/dietary-supplements/omega3-supplement.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 10,
    "name": "مكمل بروبيوتيك",
    "name_ar": "مكمل بروبيوتيك",
    "slug": "supplements-probiotic",
    "description": "Premium Probiotic for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل بروبيوتيك الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 144,
    "original_price": null,
    "currency": "MAD",
    "stock": 37,
    "images": [
      "/images/dietary-supplements/probiotic.jpg"
    ],
    "image_url": "/images/dietary-supplements/probiotic.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 11,
    "name": "مكمل شيلاجيت",
    "name_ar": "مكمل شيلاجيت",
    "slug": "supplements-shilajit",
    "description": "Premium Shilajit for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل شيلاجيت الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 130,
    "original_price": null,
    "currency": "MAD",
    "stock": 47,
    "images": [
      "/images/dietary-supplements/shilajit.jpg"
    ],
    "image_url": "/images/dietary-supplements/shilajit.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 12,
    "name": "مكمل فيتامين D3 + K2",
    "name_ar": "مكمل فيتامين D3 + K2",
    "slug": "supplements-vitamin-d3-k2",
    "description": "Premium Vitamin D3 K2 for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل فيتامين D3 + K2 الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 171,
    "original_price": null,
    "currency": "MAD",
    "stock": 26,
    "images": [
      "/images/dietary-supplements/vitamin-d3-k2.jpg"
    ],
    "image_url": "/images/dietary-supplements/vitamin-d3-k2.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 13,
    "name": "مكمل زنك",
    "name_ar": "مكمل زنك",
    "slug": "supplements-zinc",
    "description": "Premium Zinc for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل زنك الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 68,
    "original_price": null,
    "currency": "MAD",
    "stock": 15,
    "images": [
      "/images/dietary-supplements/zinc.jpg"
    ],
    "image_url": "/images/dietary-supplements/zinc.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 14,
    "name": "أعشاب اليانسون",
    "name_ar": "أعشاب اليانسون",
    "slug": "herbs-anise-herb",
    "description": "Premium Anise for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب اليانسون طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 180,
    "original_price": null,
    "currency": "MAD",
    "stock": 49,
    "images": [
      "/images/medicinal-herbs/Ashwagandha.jpg"
    ],
    "image_url": "/images/medicinal-herbs/Ashwagandha.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 15,
    "name": "أعشاب البابونج",
    "name_ar": "أعشاب البابونج",
    "slug": "herbs-camomile-herb",
    "description": "Premium Camomile for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب البابونج طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 249,
    "original_price": null,
    "currency": "MAD",
    "stock": 27,
    "images": [
      "/images/medicinal-herbs/camomile-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/camomile-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 16,
    "name": "أعشاب القرفة",
    "name_ar": "أعشاب القرفة",
    "slug": "herbs-cinnamon-herb",
    "description": "Premium Cinnamon for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب القرفة طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 47,
    "original_price": null,
    "currency": "MAD",
    "stock": 56,
    "images": [
      "/images/medicinal-herbs/camomile-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/camomile-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 17,
    "name": "أعشاب الزنجبيل",
    "name_ar": "أعشاب الزنجبيل",
    "slug": "herbs-ginger-herb",
    "description": "Premium Ginger for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب الزنجبيل طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 235,
    "original_price": null,
    "currency": "MAD",
    "stock": 35,
    "images": [
      "/images/medicinal-herbs/ginger-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/ginger-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 18,
    "name": "أعشاب الكركديه",
    "name_ar": "أعشاب الكركديه",
    "slug": "herbs-hibiscus-herb",
    "description": "Premium Hibiscus for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب الكركديه طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 86,
    "original_price": null,
    "currency": "MAD",
    "stock": 45,
    "images": [
      "/images/medicinal-herbs/ginger-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/ginger-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 19,
    "name": "أعشاب لافندر (خزامى)",
    "name_ar": "أعشاب لافندر (خزامى)",
    "slug": "herbs-lavender-herb",
    "description": "Premium Lavender for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب لافندر (خزامى) طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 107,
    "original_price": null,
    "currency": "MAD",
    "stock": 52,
    "images": [
      "/images/medicinal-herbs/Eucalyptus.jpg"
    ],
    "image_url": "/images/medicinal-herbs/Eucalyptus.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 20,
    "name": "أعشاب اللويزة",
    "name_ar": "أعشاب اللويزة",
    "slug": "herbs-lemon-verbena-herb",
    "description": "Premium Lemon Verbena for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب اللويزة طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 192,
    "original_price": null,
    "currency": "MAD",
    "stock": 51,
    "images": [
      "/images/medicinal-herbs/Foeniculum.jpg"
    ],
    "image_url": "/images/medicinal-herbs/Foeniculum.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 21,
    "name": "أعشاب النعناع",
    "name_ar": "أعشاب النعناع",
    "slug": "herbs-mint-herb",
    "description": "Premium Mint for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب النعناع طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 110,
    "original_price": null,
    "currency": "MAD",
    "stock": 30,
    "images": [
      "/images/medicinal-herbs/Ginseng.jpg"
    ],
    "image_url": "/images/medicinal-herbs/Ginseng.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 22,
    "name": "أعشاب إكليل الجبل",
    "name_ar": "أعشاب إكليل الجبل",
    "slug": "herbs-rosemary-herb",
    "description": "Premium Rosemary for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب إكليل الجبل طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 96,
    "original_price": null,
    "currency": "MAD",
    "stock": 17,
    "images": [
      "/images/medicinal-herbs/Maca.jpg"
    ],
    "image_url": "/images/medicinal-herbs/Maca.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 23,
    "name": "أعشاب المريمية",
    "name_ar": "أعشاب المريمية",
    "slug": "herbs-sage-herb",
    "description": "Premium Sage for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب المريمية طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 205,
    "original_price": null,
    "currency": "MAD",
    "stock": 27,
    "images": [
      "/images/medicinal-herbs/Saints.jpg"
    ],
    "image_url": "/images/medicinal-herbs/Saints.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 24,
    "name": "أعشاب الزعتر",
    "name_ar": "أعشاب الزعتر",
    "slug": "herbs-thyme-herb",
    "description": "Premium Thyme for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب الزعتر طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 143,
    "original_price": null,
    "currency": "MAD",
    "stock": 52,
    "images": [
      "/images/medicinal-herbs/Thyme.jpg"
    ],
    "image_url": "/images/medicinal-herbs/Thyme.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 25,
    "name": "أعشاب الكركم",
    "name_ar": "أعشاب الكركم",
    "slug": "herbs-turmeric-herb",
    "description": "Premium Turmeric for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب الكركم طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 125,
    "original_price": null,
    "currency": "MAD",
    "stock": 33,
    "images": [
      "/images/medicinal-herbs/Moringa.jpg"
    ],
    "image_url": "/images/medicinal-herbs/Moringa.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 26,
    "name": "زيت Almond العضوي",
    "name_ar": "زيت Almond العضوي",
    "slug": "oils-almond-oil",
    "description": "Premium Almond for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت Almond العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 69,
    "original_price": null,
    "currency": "MAD",
    "stock": 39,
    "images": [
      "/images/medicinal-oils/almond-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/almond-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 27,
    "name": "زيت أرغان العضوي",
    "name_ar": "زيت أرغان العضوي",
    "slug": "oils-argan-oil",
    "description": "Premium Argan for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت أرغان العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 215,
    "original_price": null,
    "currency": "MAD",
    "stock": 14,
    "images": [
      "/images/medicinal-oils/argan-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/argan-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 28,
    "name": "زيت حبة البركة العضوي",
    "name_ar": "زيت حبة البركة العضوي",
    "slug": "oils-black-seed-oil",
    "description": "Premium Black Seed for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت حبة البركة العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 132,
    "original_price": null,
    "currency": "MAD",
    "stock": 17,
    "images": [
      "/images/medicinal-oils/black-seed-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/black-seed-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 29,
    "name": "زيت خروع العضوي",
    "name_ar": "زيت خروع العضوي",
    "slug": "oils-castor-oil",
    "description": "Premium Castor for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت خروع العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 197,
    "original_price": null,
    "currency": "MAD",
    "stock": 22,
    "images": [
      "/images/medicinal-oils/castor-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/castor-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 30,
    "name": "زيت Ginger العضوي",
    "name_ar": "زيت Ginger العضوي",
    "slug": "oils-ginger-oil",
    "description": "Premium Ginger for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت Ginger العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 181,
    "original_price": null,
    "currency": "MAD",
    "stock": 15,
    "images": [
      "/images/medicinal-oils/ginger-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/ginger-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 31,
    "name": "زيت Gratic العضوي",
    "name_ar": "زيت Gratic العضوي",
    "slug": "oils-gratic-oil",
    "description": "Premium Gratic for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت Gratic العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 71,
    "original_price": null,
    "currency": "MAD",
    "stock": 52,
    "images": [
      "/images/medicinal-oils/gratic-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/gratic-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 32,
    "name": "زيت Lanvender العضوي",
    "name_ar": "زيت Lanvender العضوي",
    "slug": "oils-lanvender-oil",
    "description": "Premium Lanvender for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت Lanvender العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 64,
    "original_price": null,
    "currency": "MAD",
    "stock": 48,
    "images": [
      "/images/medicinal-oils/lanvender-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/lanvender-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 33,
    "name": "زيت Musk العضوي",
    "name_ar": "زيت Musk العضوي",
    "slug": "oils-musk-oil",
    "description": "Premium Musk for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت Musk العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 170,
    "original_price": null,
    "currency": "MAD",
    "stock": 59,
    "images": [
      "/images/medicinal-oils/musk-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/musk-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 34,
    "name": "زيت زيتون العضوي",
    "name_ar": "زيت زيتون العضوي",
    "slug": "oils-olive-oil",
    "description": "Premium Olive for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت زيتون العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 212,
    "original_price": null,
    "currency": "MAD",
    "stock": 33,
    "images": [
      "/images/medicinal-oils/olive-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/olive-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 35,
    "name": "زيت Rose العضوي",
    "name_ar": "زيت Rose العضوي",
    "slug": "oils-rose-oil",
    "description": "Premium Rose for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت Rose العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 202,
    "original_price": null,
    "currency": "MAD",
    "stock": 21,
    "images": [
      "/images/medicinal-oils/rose-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/rose-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 36,
    "name": "زيت سدر العضوي",
    "name_ar": "زيت سدر العضوي",
    "slug": "oils-sidr-oil",
    "description": "Premium Sidr for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت سدر العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 158,
    "original_price": null,
    "currency": "MAD",
    "stock": 36,
    "images": [
      "/images/medicinal-oils/sidr-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/sidr-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 37,
    "name": "عسل طلح طبيعي",
    "name_ar": "عسل طلح طبيعي",
    "slug": "honey-acacia-honey",
    "description": "Premium Acacia for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل طلح طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 120,
    "original_price": null,
    "currency": "MAD",
    "stock": 20,
    "images": [
      "/images/natural-honey/acacia-honey.jpg"
    ],
    "image_url": "/images/natural-honey/acacia-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 38,
    "name": "عسل Blackseed طبيعي",
    "name_ar": "عسل Blackseed طبيعي",
    "slug": "honey-blackseed-honey",
    "description": "Premium Blackseed for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Blackseed طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 231,
    "original_price": null,
    "currency": "MAD",
    "stock": 59,
    "images": [
      "/images/natural-honey/blackseed-honey.jpg"
    ],
    "image_url": "/images/natural-honey/blackseed-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 39,
    "name": "عسل Carob طبيعي",
    "name_ar": "عسل Carob طبيعي",
    "slug": "honey-carob-honey",
    "description": "Premium Carob for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Carob طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 94,
    "original_price": null,
    "currency": "MAD",
    "stock": 30,
    "images": [
      "/images/natural-honey/carob-honey.jpg"
    ],
    "image_url": "/images/natural-honey/carob-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 40,
    "name": "عسل Daghmos طبيعي",
    "name_ar": "عسل Daghmos طبيعي",
    "slug": "honey-daghmos-honey",
    "description": "Premium Daghmos for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Daghmos طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 91,
    "original_price": null,
    "currency": "MAD",
    "stock": 28,
    "images": [
      "/images/natural-honey/daghmos-honey.jpg"
    ],
    "image_url": "/images/natural-honey/daghmos-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 41,
    "name": "عسل كافور طبيعي",
    "name_ar": "عسل كافور طبيعي",
    "slug": "honey-eucalyptus-honey",
    "description": "Premium Eucalyptus for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل كافور طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 184,
    "original_price": null,
    "currency": "MAD",
    "stock": 34,
    "images": [
      "/images/natural-honey/eucalyptus-honey.jpg"
    ],
    "image_url": "/images/natural-honey/eucalyptus-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 42,
    "name": "عسل Flower طبيعي",
    "name_ar": "عسل Flower طبيعي",
    "slug": "honey-flower-honey",
    "description": "Premium Flower for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Flower طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 136,
    "original_price": null,
    "currency": "MAD",
    "stock": 52,
    "images": [
      "/images/natural-honey/flower-honey.jpg"
    ],
    "image_url": "/images/natural-honey/flower-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 43,
    "name": "عسل Forest طبيعي",
    "name_ar": "عسل Forest طبيعي",
    "slug": "honey-forest-honey",
    "description": "Premium Forest for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Forest طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 128,
    "original_price": null,
    "currency": "MAD",
    "stock": 26,
    "images": [
      "/images/natural-honey/forest-honey.jpg"
    ],
    "image_url": "/images/natural-honey/forest-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 44,
    "name": "عسل مانوكا طبيعي",
    "name_ar": "عسل مانوكا طبيعي",
    "slug": "honey-manuka-honey",
    "description": "Premium Manuka for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل مانوكا طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 184,
    "original_price": null,
    "currency": "MAD",
    "stock": 59,
    "images": [
      "/images/natural-honey/manuka-honey.jpg"
    ],
    "image_url": "/images/natural-honey/manuka-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 45,
    "name": "عسل Orange Blossom طبيعي",
    "name_ar": "عسل Orange Blossom طبيعي",
    "slug": "honey-orange-blossom-honey",
    "description": "Premium Orange Blossom for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Orange Blossom طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 173,
    "original_price": null,
    "currency": "MAD",
    "stock": 54,
    "images": [
      "/images/natural-honey/orange-blossom-honey.jpg"
    ],
    "image_url": "/images/natural-honey/orange-blossom-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 46,
    "name": "عسل سدر طبيعي",
    "name_ar": "عسل سدر طبيعي",
    "slug": "honey-sidr-honey",
    "description": "Premium Sidr for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل سدر طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 119,
    "original_price": null,
    "currency": "MAD",
    "stock": 16,
    "images": [
      "/images/natural-honey/sidr-honey.jpg"
    ],
    "image_url": "/images/natural-honey/sidr-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 47,
    "name": "عسل Thyme طبيعي",
    "name_ar": "عسل Thyme طبيعي",
    "slug": "honey-thyme-honey",
    "description": "Premium Thyme for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Thyme طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 198,
    "original_price": null,
    "currency": "MAD",
    "stock": 58,
    "images": [
      "/images/natural-honey/thyme-honey.jpg"
    ],
    "image_url": "/images/natural-honey/thyme-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 48,
    "name": "عسل Wildflower طبيعي",
    "name_ar": "عسل Wildflower طبيعي",
    "slug": "honey-wildflower-honey",
    "description": "Premium Wildflower for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Wildflower طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 199,
    "original_price": null,
    "currency": "MAD",
    "stock": 50,
    "images": [
      "/images/natural-honey/wildflower-honey.jpg"
    ],
    "image_url": "/images/natural-honey/wildflower-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  }
  ,{
    "id": 100,
    "name": "Anise Herbal Tea",
    "name_ar": "شاي اليانسون",
    "slug": "herbal-tea-anise-herbal-tea",
    "description": "Premium organic anise herbal tea for relaxation and wellness. Made with 100% natural ingredients.",
    "description_ar": "شاي اليانسون عضوي وممتاز للاسترخاء والصحة العامة.",
    "price": 45,
    "original_price": null,
    "currency": "MAD",
    "stock": 100,
    "images": [
      "/images/herbal tea/anise-herb.jpg"
    ],
    "image_url": "/images/herbal tea/anise-herb.jpg",
    "category_id": 5,
    "is_active": true,
    "featured": true,
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
  ,{
    "id": 101,
    "name": "Chamomile Herbal Tea",
    "name_ar": "شاي البابونج",
    "slug": "herbal-tea-chamomile-herbal-tea",
    "description": "Premium organic chamomile herbal tea for relaxation and wellness. Made with 100% natural ingredients.",
    "description_ar": "شاي البابونج عضوي وممتاز للاسترخاء والصحة العامة.",
    "price": 55,
    "original_price": null,
    "currency": "MAD",
    "stock": 100,
    "images": [
      "/images/herbal tea/camomile-herb.jpg"
    ],
    "image_url": "/images/herbal tea/camomile-herb.jpg",
    "category_id": 5,
    "is_active": true,
    "featured": true,
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
  ,{
    "id": 102,
    "name": "Cinnamon Herbal Tea",
    "name_ar": "شاي القرفة",
    "slug": "herbal-tea-cinnamon-herbal-tea",
    "description": "Premium organic cinnamon herbal tea for relaxation and wellness. Made with 100% natural ingredients.",
    "description_ar": "شاي القرفة عضوي وممتاز للاسترخاء والصحة العامة.",
    "price": 50,
    "original_price": null,
    "currency": "MAD",
    "stock": 100,
    "images": [
      "/images/herbal tea/cinnamon-herb.jpg"
    ],
    "image_url": "/images/herbal tea/cinnamon-herb.jpg",
    "category_id": 5,
    "is_active": true,
    "featured": true,
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
  ,{
    "id": 103,
    "name": "Ginger Herbal Tea",
    "name_ar": "شاي الزنجبيل",
    "slug": "herbal-tea-ginger-herbal-tea",
    "description": "Premium organic ginger herbal tea for relaxation and wellness. Made with 100% natural ingredients.",
    "description_ar": "شاي الزنجبيل عضوي وممتاز للاسترخاء والصحة العامة.",
    "price": 60,
    "original_price": null,
    "currency": "MAD",
    "stock": 100,
    "images": [
      "/images/herbal tea/ginger-herb.jpg"
    ],
    "image_url": "/images/herbal tea/ginger-herb.jpg",
    "category_id": 5,
    "is_active": true,
    "featured": true,
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
  ,{
    "id": 104,
    "name": "Mixed Herbal Tea",
    "name_ar": "شاي أعشاب مشكلة",
    "slug": "herbal-tea-mixed-herbal-tea",
    "description": "Premium organic mixed herbal tea for relaxation and wellness. Made with 100% natural ingredients.",
    "description_ar": "شاي أعشاب مشكلة عضوي وممتاز للاسترخاء والصحة العامة.",
    "price": 55,
    "original_price": null,
    "currency": "MAD",
    "stock": 100,
    "images": [
      "/images/herbal tea/herb-tea-2.jpg"
    ],
    "image_url": "/images/herbal tea/herb-tea-2.jpg",
    "category_id": 5,
    "is_active": true,
    "featured": true,
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
  ,{
    "id": 105,
    "name": "Hibiscus Herbal Tea",
    "name_ar": "شاي الكركديه",
    "slug": "herbal-tea-hibiscus-herbal-tea",
    "description": "Premium organic hibiscus herbal tea for relaxation and wellness. Made with 100% natural ingredients.",
    "description_ar": "شاي الكركديه عضوي وممتاز للاسترخاء والصحة العامة.",
    "price": 45,
    "original_price": null,
    "currency": "MAD",
    "stock": 100,
    "images": [
      "/images/herbal tea/hibiscus-herb.jpg"
    ],
    "image_url": "/images/herbal tea/hibiscus-herb.jpg",
    "category_id": 5,
    "is_active": true,
    "featured": true,
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
  ,{
    "id": 106,
    "name": "Lavender Herbal Tea",
    "name_ar": "شاي الخزامى",
    "slug": "herbal-tea-lavender-herbal-tea",
    "description": "Premium organic lavender herbal tea for relaxation and wellness. Made with 100% natural ingredients.",
    "description_ar": "شاي الخزامى عضوي وممتاز للاسترخاء والصحة العامة.",
    "price": 70,
    "original_price": null,
    "currency": "MAD",
    "stock": 100,
    "images": [
      "/images/herbal tea/lavender-herb.jpg"
    ],
    "image_url": "/images/herbal tea/lavender-herb.jpg",
    "category_id": 5,
    "is_active": true,
    "featured": true,
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
  ,{
    "id": 107,
    "name": "Lemon Verbena Tea",
    "name_ar": "شاي اللويزة",
    "slug": "herbal-tea-lemon-verbena-tea",
    "description": "Premium organic lemon verbena tea for relaxation and wellness. Made with 100% natural ingredients.",
    "description_ar": "شاي اللويزة عضوي وممتاز للاسترخاء والصحة العامة.",
    "price": 50,
    "original_price": null,
    "currency": "MAD",
    "stock": 100,
    "images": [
      "/images/herbal tea/lemon-verbena-herb.jpg"
    ],
    "image_url": "/images/herbal tea/lemon-verbena-herb.jpg",
    "category_id": 5,
    "is_active": true,
    "featured": true,
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
  ,{
    "id": 108,
    "name": "Mint Herbal Tea",
    "name_ar": "شاي النعناع",
    "slug": "herbal-tea-mint-herbal-tea",
    "description": "Premium organic mint herbal tea for relaxation and wellness. Made with 100% natural ingredients.",
    "description_ar": "شاي النعناع عضوي وممتاز للاسترخاء والصحة العامة.",
    "price": 40,
    "original_price": null,
    "currency": "MAD",
    "stock": 100,
    "images": [
      "/images/herbal tea/mint-herb.jpg"
    ],
    "image_url": "/images/herbal tea/mint-herb.jpg",
    "category_id": 5,
    "is_active": true,
    "featured": true,
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
  ,{
    "id": 109,
    "name": "Rosemary Herbal Tea",
    "name_ar": "شاي إكليل الجبل",
    "slug": "herbal-tea-rosemary-herbal-tea",
    "description": "Premium organic rosemary herbal tea for relaxation and wellness. Made with 100% natural ingredients.",
    "description_ar": "شاي إكليل الجبل عضوي وممتاز للاسترخاء والصحة العامة.",
    "price": 45,
    "original_price": null,
    "currency": "MAD",
    "stock": 100,
    "images": [
      "/images/herbal tea/rosemary-herb.jpg"
    ],
    "image_url": "/images/herbal tea/rosemary-herb.jpg",
    "category_id": 5,
    "is_active": true,
    "featured": true,
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
  ,{
    "id": 110,
    "name": "Sage Herbal Tea",
    "name_ar": "شاي المريمية",
    "slug": "herbal-tea-sage-herbal-tea",
    "description": "Premium organic sage herbal tea for relaxation and wellness. Made with 100% natural ingredients.",
    "description_ar": "شاي المريمية عضوي وممتاز للاسترخاء والصحة العامة.",
    "price": 50,
    "original_price": null,
    "currency": "MAD",
    "stock": 100,
    "images": [
      "/images/herbal tea/sage-herb.jpg"
    ],
    "image_url": "/images/herbal tea/sage-herb.jpg",
    "category_id": 5,
    "is_active": true,
    "featured": true,
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
  ,{
    "id": 111,
    "name": "Thyme Herbal Tea",
    "name_ar": "شاي الزعتر",
    "slug": "herbal-tea-thyme-herbal-tea",
    "description": "Premium organic thyme herbal tea for relaxation and wellness. Made with 100% natural ingredients.",
    "description_ar": "شاي الزعتر عضوي وممتاز للاسترخاء والصحة العامة.",
    "price": 45,
    "original_price": null,
    "currency": "MAD",
    "stock": 100,
    "images": [
      "/images/herbal tea/thyme-herb.jpg"
    ],
    "image_url": "/images/herbal tea/thyme-herb.jpg",
    "category_id": 5,
    "is_active": true,
    "featured": true,
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
  ,{
    "id": 112,
    "name": "Turmeric Herbal Tea",
    "name_ar": "شاي الكركم",
    "slug": "herbal-tea-turmeric-herbal-tea",
    "description": "Premium organic turmeric herbal tea for relaxation and wellness. Made with 100% natural ingredients.",
    "description_ar": "شاي الكركم عضوي وممتاز للاسترخاء والصحة العامة.",
    "price": 55,
    "original_price": null,
    "currency": "MAD",
    "stock": 100,
    "images": [
      "/images/herbal tea/turmeric-herb.jpg"
    ],
    "image_url": "/images/herbal tea/turmeric-herb.jpg",
    "category_id": 5,
    "is_active": true,
    "featured": true,
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
];
