// THIS FILE IS AUTOMATICALLY GENERATED FROM PROJECT IMAGES
import { Category, Product } from './products'

export const demoCategories: Category[] = [
  {
    "id": 1,
    "slug": "supplements",
    "name": "Dietary Supplements",
    "name_ar": "مكملات غذائية",
    "description": "Real dietary supplements from catalog",
    "description_ar": "مكملات غذائية أصلية من الكتالوج",
    "image": "/images/categories/supplements.jpg",
    "created_at": "2026-03-04T15:15:36.184Z",
    "updated_at": "2026-03-04T15:15:36.185Z"
  },
  {
    "id": 2,
    "slug": "herbs",
    "name": "Medicinal Herbs",
    "name_ar": "أعشاب طبية",
    "description": "Organic medicinal herbs",
    "description_ar": "أعشاب طبية عضوية",
    "image": "/images/categories/herbs.jpg",
    "created_at": "2026-03-04T15:15:36.185Z",
    "updated_at": "2026-03-04T15:15:36.185Z"
  },
  {
    "id": 3,
    "slug": "oils",
    "name": "Medicinal Oils",
    "name_ar": "زيوت علاجية",
    "description": "Pure medicinal & essential oils",
    "description_ar": "زيوت علاجية وعطرية نقية",
    "image": "/images/categories/oils.jpg",
    "created_at": "2026-03-04T15:15:36.185Z",
    "updated_at": "2026-03-04T15:15:36.185Z"
  },
  {
    "id": 4,
    "slug": "honey",
    "name": "Natural Honey",
    "name_ar": "عسل طبيعي",
    "description": "100% pure natural honey",
    "description_ar": "عسل طبيعي 100%",
    "image": "/images/categories/honey.jpg",
    "created_at": "2026-03-04T15:15:36.185Z",
    "updated_at": "2026-03-04T15:15:36.185Z"
  }
];

export const demoProducts: Product[] = [
  {
    "id": 1,
    "name": "Ashwagandha",
    "name_ar": "مكمل أشواجاندا",
    "slug": "supplements-ashwagandha",
    "description": "Premium Ashwagandha for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل أشواجاندا الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 123,
    "currency": "MAD",
    "stock": 42,
    "images": [
      "/images/dietary-supplements/ashwagandha.jpg"
    ],
    "image_url": "/images/dietary-supplements/ashwagandha.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 2,
    "name": "Biotin",
    "name_ar": "مكمل بيوتين",
    "slug": "supplements-biotin",
    "description": "Premium Biotin for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل بيوتين الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 224,
    "currency": "MAD",
    "stock": 58,
    "images": [
      "/images/dietary-supplements/biotin.jpg"
    ],
    "image_url": "/images/dietary-supplements/biotin.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 3,
    "name": "Collagen",
    "name_ar": "مكمل كولاجين",
    "slug": "supplements-collagen",
    "description": "Premium Collagen for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل كولاجين الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 204,
    "currency": "MAD",
    "stock": 33,
    "images": [
      "/images/dietary-supplements/collagen.jpg"
    ],
    "image_url": "/images/dietary-supplements/collagen.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 4,
    "name": "L Glutathione",
    "name_ar": "مكمل إل-جلوتاثيون",
    "slug": "supplements-l-glutathione",
    "description": "Premium L Glutathione for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل إل-جلوتاثيون الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 141,
    "currency": "MAD",
    "stock": 12,
    "images": [
      "/images/dietary-supplements/l-glutathione.jpg"
    ],
    "image_url": "/images/dietary-supplements/l-glutathione.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 5,
    "name": "Magnesium",
    "name_ar": "مكمل مغنيسيوم",
    "slug": "supplements-magnesium",
    "description": "Premium Magnesium for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل مغنيسيوم الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 191,
    "currency": "MAD",
    "stock": 35,
    "images": [
      "/images/dietary-supplements/magnesium.jpg"
    ],
    "image_url": "/images/dietary-supplements/magnesium.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 6,
    "name": "Mastic Gum",
    "name_ar": "مكمل مستكة",
    "slug": "supplements-mastic-gum",
    "description": "Premium Mastic Gum for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل مستكة الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 145,
    "currency": "MAD",
    "stock": 17,
    "images": [
      "/images/dietary-supplements/mastic-gum.jpg"
    ],
    "image_url": "/images/dietary-supplements/mastic-gum.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 7,
    "name": "Multivitamins",
    "name_ar": "مكمل فيتامينات متعددة",
    "slug": "supplements-multivitamins",
    "description": "Premium Multivitamins for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل فيتامينات متعددة الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 92,
    "currency": "MAD",
    "stock": 19,
    "images": [
      "/images/dietary-supplements/multivitamins.jpg"
    ],
    "image_url": "/images/dietary-supplements/multivitamins.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 8,
    "name": "Omega 3 Fish",
    "name_ar": "مكمل Omega 3 Fish",
    "slug": "supplements-omega-3-fish-oil",
    "description": "Premium Omega 3 Fish for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل Omega 3 Fish الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 148,
    "currency": "MAD",
    "stock": 21,
    "images": [
      "/images/dietary-supplements/omega-3-fish-oil.jpg"
    ],
    "image_url": "/images/dietary-supplements/omega-3-fish-oil.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 9,
    "name": "Omega3 Supplement",
    "name_ar": "مكمل مكمل أوميغا 3",
    "slug": "supplements-omega3-supplement",
    "description": "Premium Omega3 Supplement for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل مكمل أوميغا 3 الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 244,
    "currency": "MAD",
    "stock": 34,
    "images": [
      "/images/dietary-supplements/omega3-supplement.jpg"
    ],
    "image_url": "/images/dietary-supplements/omega3-supplement.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 10,
    "name": "Probiotic",
    "name_ar": "مكمل بروبيوتيك",
    "slug": "supplements-probiotic",
    "description": "Premium Probiotic for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل بروبيوتيك الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 144,
    "currency": "MAD",
    "stock": 37,
    "images": [
      "/images/dietary-supplements/probiotic.jpg"
    ],
    "image_url": "/images/dietary-supplements/probiotic.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 11,
    "name": "Shilajit",
    "name_ar": "مكمل شيلاجيت",
    "slug": "supplements-shilajit",
    "description": "Premium Shilajit for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل شيلاجيت الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 130,
    "currency": "MAD",
    "stock": 47,
    "images": [
      "/images/dietary-supplements/shilajit.jpg"
    ],
    "image_url": "/images/dietary-supplements/shilajit.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 12,
    "name": "Vitamin D3 K2",
    "name_ar": "مكمل فيتامين D3 + K2",
    "slug": "supplements-vitamin-d3-k2",
    "description": "Premium Vitamin D3 K2 for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل فيتامين D3 + K2 الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 171,
    "currency": "MAD",
    "stock": 26,
    "images": [
      "/images/dietary-supplements/vitamin-d3-k2.jpg"
    ],
    "image_url": "/images/dietary-supplements/vitamin-d3-k2.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 13,
    "name": "Zinc",
    "name_ar": "مكمل زنك",
    "slug": "supplements-zinc",
    "description": "Premium Zinc for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "مكمل زنك الممتاز لدعم صحتك العامة وتعزيز نشاطك اليومي.",
    "price": 68,
    "currency": "MAD",
    "stock": 15,
    "images": [
      "/images/dietary-supplements/zinc.jpg"
    ],
    "image_url": "/images/dietary-supplements/zinc.jpg",
    "category_id": 1,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 14,
    "name": "Anise",
    "name_ar": "أعشاب اليانسون",
    "slug": "herbs-anise-herb",
    "description": "Premium Anise for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب اليانسون طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 180,
    "currency": "MAD",
    "stock": 49,
    "images": [
      "/images/medicinal-herbs/anise-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/anise-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 15,
    "name": "Camomile",
    "name_ar": "أعشاب البابونج",
    "slug": "herbs-camomile-herb",
    "description": "Premium Camomile for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب البابونج طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 249,
    "currency": "MAD",
    "stock": 27,
    "images": [
      "/images/medicinal-herbs/camomile-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/camomile-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 16,
    "name": "Cinnamon",
    "name_ar": "أعشاب القرفة",
    "slug": "herbs-cinnamon-herb",
    "description": "Premium Cinnamon for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب القرفة طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 47,
    "currency": "MAD",
    "stock": 56,
    "images": [
      "/images/medicinal-herbs/cinnamon-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/cinnamon-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 17,
    "name": "Ginger",
    "name_ar": "أعشاب الزنجبيل",
    "slug": "herbs-ginger-herb",
    "description": "Premium Ginger for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب الزنجبيل طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 235,
    "currency": "MAD",
    "stock": 35,
    "images": [
      "/images/medicinal-herbs/ginger-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/ginger-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 18,
    "name": "Hibiscus",
    "name_ar": "أعشاب الكركديه",
    "slug": "herbs-hibiscus-herb",
    "description": "Premium Hibiscus for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب الكركديه طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 86,
    "currency": "MAD",
    "stock": 45,
    "images": [
      "/images/medicinal-herbs/hibiscus-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/hibiscus-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 19,
    "name": "Lavender",
    "name_ar": "أعشاب لافندر (خزامى)",
    "slug": "herbs-lavender-herb",
    "description": "Premium Lavender for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب لافندر (خزامى) طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 107,
    "currency": "MAD",
    "stock": 52,
    "images": [
      "/images/medicinal-herbs/lavender-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/lavender-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 20,
    "name": "Lemon Verbena",
    "name_ar": "أعشاب اللويزة",
    "slug": "herbs-lemon-verbena-herb",
    "description": "Premium Lemon Verbena for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب اللويزة طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 192,
    "currency": "MAD",
    "stock": 51,
    "images": [
      "/images/medicinal-herbs/lemon-verbena-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/lemon-verbena-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 21,
    "name": "Mint",
    "name_ar": "أعشاب النعناع",
    "slug": "herbs-mint-herb",
    "description": "Premium Mint for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب النعناع طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 110,
    "currency": "MAD",
    "stock": 30,
    "images": [
      "/images/medicinal-herbs/mint-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/mint-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 22,
    "name": "Rosemary",
    "name_ar": "أعشاب إكليل الجبل",
    "slug": "herbs-rosemary-herb",
    "description": "Premium Rosemary for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب إكليل الجبل طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 96,
    "currency": "MAD",
    "stock": 17,
    "images": [
      "/images/medicinal-herbs/rosemary-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/rosemary-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 23,
    "name": "Sage",
    "name_ar": "أعشاب المريمية",
    "slug": "herbs-sage-herb",
    "description": "Premium Sage for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب المريمية طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 205,
    "currency": "MAD",
    "stock": 27,
    "images": [
      "/images/medicinal-herbs/sage-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/sage-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 24,
    "name": "Thyme",
    "name_ar": "أعشاب الزعتر",
    "slug": "herbs-thyme-herb",
    "description": "Premium Thyme for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب الزعتر طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 143,
    "currency": "MAD",
    "stock": 52,
    "images": [
      "/images/medicinal-herbs/thyme-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/thyme-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.187Z",
    "updated_at": "2026-03-04T15:15:36.187Z"
  },
  {
    "id": 25,
    "name": "Turmeric",
    "name_ar": "أعشاب الكركم",
    "slug": "herbs-turmeric-herb",
    "description": "Premium Turmeric for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "أعشاب الكركم طبيعية وعضوية، مثالية للاستخدام اليومي.",
    "price": 125,
    "currency": "MAD",
    "stock": 33,
    "images": [
      "/images/medicinal-herbs/turmeric-herb.jpg"
    ],
    "image_url": "/images/medicinal-herbs/turmeric-herb.jpg",
    "category_id": 2,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 26,
    "name": "Almond",
    "name_ar": "زيت Almond العضوي",
    "slug": "oils-almond-oil",
    "description": "Premium Almond for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت Almond العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 69,
    "currency": "MAD",
    "stock": 39,
    "images": [
      "/images/medicinal-oils/almond-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/almond-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 27,
    "name": "Argan",
    "name_ar": "زيت أرغان العضوي",
    "slug": "oils-argan-oil",
    "description": "Premium Argan for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت أرغان العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 215,
    "currency": "MAD",
    "stock": 14,
    "images": [
      "/images/medicinal-oils/argan-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/argan-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 28,
    "name": "Black Seed",
    "name_ar": "زيت حبة البركة العضوي",
    "slug": "oils-black-seed-oil",
    "description": "Premium Black Seed for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت حبة البركة العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 132,
    "currency": "MAD",
    "stock": 17,
    "images": [
      "/images/medicinal-oils/black-seed-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/black-seed-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 29,
    "name": "Castor",
    "name_ar": "زيت خروع العضوي",
    "slug": "oils-castor-oil",
    "description": "Premium Castor for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت خروع العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 197,
    "currency": "MAD",
    "stock": 22,
    "images": [
      "/images/medicinal-oils/castor-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/castor-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 30,
    "name": "Ginger",
    "name_ar": "زيت Ginger العضوي",
    "slug": "oils-ginger-oil",
    "description": "Premium Ginger for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت Ginger العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 181,
    "currency": "MAD",
    "stock": 15,
    "images": [
      "/images/medicinal-oils/ginger-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/ginger-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 31,
    "name": "Gratic",
    "name_ar": "زيت Gratic العضوي",
    "slug": "oils-gratic-oil",
    "description": "Premium Gratic for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت Gratic العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 71,
    "currency": "MAD",
    "stock": 52,
    "images": [
      "/images/medicinal-oils/gratic-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/gratic-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 32,
    "name": "Lanvender",
    "name_ar": "زيت Lanvender العضوي",
    "slug": "oils-lanvender-oil",
    "description": "Premium Lanvender for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت Lanvender العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 64,
    "currency": "MAD",
    "stock": 48,
    "images": [
      "/images/medicinal-oils/lanvender-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/lanvender-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 33,
    "name": "Musk",
    "name_ar": "زيت Musk العضوي",
    "slug": "oils-musk-oil",
    "description": "Premium Musk for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت Musk العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 170,
    "currency": "MAD",
    "stock": 59,
    "images": [
      "/images/medicinal-oils/musk-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/musk-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 34,
    "name": "Olive",
    "name_ar": "زيت زيتون العضوي",
    "slug": "oils-olive-oil",
    "description": "Premium Olive for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت زيتون العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 212,
    "currency": "MAD",
    "stock": 33,
    "images": [
      "/images/medicinal-oils/olive-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/olive-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 35,
    "name": "Rose",
    "name_ar": "زيت Rose العضوي",
    "slug": "oils-rose-oil",
    "description": "Premium Rose for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت Rose العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 202,
    "currency": "MAD",
    "stock": 21,
    "images": [
      "/images/medicinal-oils/rose-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/rose-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 36,
    "name": "Sidr",
    "name_ar": "زيت سدر العضوي",
    "slug": "oils-sidr-oil",
    "description": "Premium Sidr for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "زيت سدر العضوي النقي، مستخلص بعناية للحفاظ على فوائده.",
    "price": 158,
    "currency": "MAD",
    "stock": 36,
    "images": [
      "/images/medicinal-oils/sidr-oil.jpg"
    ],
    "image_url": "/images/medicinal-oils/sidr-oil.jpg",
    "category_id": 3,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 37,
    "name": "Acacia",
    "name_ar": "عسل طلح طبيعي",
    "slug": "honey-acacia-honey",
    "description": "Premium Acacia for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل طلح طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 120,
    "currency": "MAD",
    "stock": 20,
    "images": [
      "/images/natural-honey/acacia-honey.jpg"
    ],
    "image_url": "/images/natural-honey/acacia-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 38,
    "name": "Blackseed",
    "name_ar": "عسل Blackseed طبيعي",
    "slug": "honey-blackseed-honey",
    "description": "Premium Blackseed for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Blackseed طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 231,
    "currency": "MAD",
    "stock": 59,
    "images": [
      "/images/natural-honey/blackseed-honey.jpg"
    ],
    "image_url": "/images/natural-honey/blackseed-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 39,
    "name": "Carob",
    "name_ar": "عسل Carob طبيعي",
    "slug": "honey-carob-honey",
    "description": "Premium Carob for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Carob طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 94,
    "currency": "MAD",
    "stock": 30,
    "images": [
      "/images/natural-honey/carob-honey.jpg"
    ],
    "image_url": "/images/natural-honey/carob-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 40,
    "name": "Daghmos",
    "name_ar": "عسل Daghmos طبيعي",
    "slug": "honey-daghmos-honey",
    "description": "Premium Daghmos for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Daghmos طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 91,
    "currency": "MAD",
    "stock": 28,
    "images": [
      "/images/natural-honey/daghmos-honey.jpg"
    ],
    "image_url": "/images/natural-honey/daghmos-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 41,
    "name": "Eucalyptus",
    "name_ar": "عسل كافور طبيعي",
    "slug": "honey-eucalyptus-honey",
    "description": "Premium Eucalyptus for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل كافور طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 184,
    "currency": "MAD",
    "stock": 34,
    "images": [
      "/images/natural-honey/eucalyptus-honey.jpg"
    ],
    "image_url": "/images/natural-honey/eucalyptus-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 42,
    "name": "Flower",
    "name_ar": "عسل Flower طبيعي",
    "slug": "honey-flower-honey",
    "description": "Premium Flower for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Flower طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 136,
    "currency": "MAD",
    "stock": 52,
    "images": [
      "/images/natural-honey/flower-honey.jpg"
    ],
    "image_url": "/images/natural-honey/flower-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 43,
    "name": "Forest",
    "name_ar": "عسل Forest طبيعي",
    "slug": "honey-forest-honey",
    "description": "Premium Forest for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Forest طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 128,
    "currency": "MAD",
    "stock": 26,
    "images": [
      "/images/natural-honey/forest-honey.jpg"
    ],
    "image_url": "/images/natural-honey/forest-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 44,
    "name": "Manuka",
    "name_ar": "عسل مانوكا طبيعي",
    "slug": "honey-manuka-honey",
    "description": "Premium Manuka for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل مانوكا طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 184,
    "currency": "MAD",
    "stock": 59,
    "images": [
      "/images/natural-honey/manuka-honey.jpg"
    ],
    "image_url": "/images/natural-honey/manuka-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 45,
    "name": "Orange Blossom",
    "name_ar": "عسل Orange Blossom طبيعي",
    "slug": "honey-orange-blossom-honey",
    "description": "Premium Orange Blossom for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Orange Blossom طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 173,
    "currency": "MAD",
    "stock": 54,
    "images": [
      "/images/natural-honey/orange-blossom-honey.jpg"
    ],
    "image_url": "/images/natural-honey/orange-blossom-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": false,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 46,
    "name": "Sidr",
    "name_ar": "عسل سدر طبيعي",
    "slug": "honey-sidr-honey",
    "description": "Premium Sidr for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل سدر طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 119,
    "currency": "MAD",
    "stock": 16,
    "images": [
      "/images/natural-honey/sidr-honey.jpg"
    ],
    "image_url": "/images/natural-honey/sidr-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 47,
    "name": "Thyme",
    "name_ar": "عسل Thyme طبيعي",
    "slug": "honey-thyme-honey",
    "description": "Premium Thyme for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Thyme طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 198,
    "currency": "MAD",
    "stock": 58,
    "images": [
      "/images/natural-honey/thyme-honey.jpg"
    ],
    "image_url": "/images/natural-honey/thyme-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  },
  {
    "id": 48,
    "name": "Wildflower",
    "name_ar": "عسل Wildflower طبيعي",
    "slug": "honey-wildflower-honey",
    "description": "Premium Wildflower for your health and wellbeing. Made with 100% natural ingredients.",
    "description_ar": "عسل Wildflower طبيعي نقي 100%، غني بالفوائد والمغذيات.",
    "price": 199,
    "currency": "MAD",
    "stock": 50,
    "images": [
      "/images/natural-honey/wildflower-honey.jpg"
    ],
    "image_url": "/images/natural-honey/wildflower-honey.jpg",
    "category_id": 4,
    "is_active": true,
    "featured": true,
    "created_at": "2026-03-04T15:15:36.188Z",
    "updated_at": "2026-03-04T15:15:36.188Z"
  }
];
